Name:           perl-App-XML-DocBook-Builder
Version:        0.1101
Release:        1%{?dist}
Summary:        Command-line utility to build DocBook documents
License:        MIT
URL:            https://metacpan.org/dist/App-XML-DocBook-Builder
Source0:        https://cpan.metacpan.org/modules/by-module/App/App-XML-DocBook-Builder-%{version}.tar.gz
BuildArch:      noarch
BuildRequires:  coreutils
BuildRequires:  perl-generators
BuildRequires:  perl-interpreter
BuildRequires:  perl(:VERSION) >= 5.14.0
BuildRequires:  perl(autodie)
BuildRequires:  perl(blib)
BuildRequires:  perl(Class::XSAccessor)
BuildRequires:  perl(File::Path)
BuildRequires:  perl(File::ShouldUpdate) >= 0.2.0
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(Getopt::Long)
BuildRequires:  perl(IO::Handle)
BuildRequires:  perl(IPC::Open3)
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(parent)
BuildRequires:  perl(Pod::Usage)
BuildRequires:  perl(strict)
BuildRequires:  perl(Test::More) >= 0.88
BuildRequires:  perl(Test::Trap)
BuildRequires:  perl(vars)
BuildRequires:  perl(warnings)
Requires:       perl(File::ShouldUpdate) >= 0.2.0

%description
Docmake is a command line tool to translate DocBook/XML code into various
resultant formats such as XHTML, RTF, PDF and XSL-FO, using the more low-level
tools. It aims to be a saner replacement, written in Perl, for xmlto, which is
written in Unix shell.

%prep
%autosetup -n App-XML-DocBook-Builder-%{version}

%package -n docmake
Summary:        Command-line utility to build DocBook documents

%description -n docmake
Docmake is a command line tool to translate DocBook/XML code into various
resultant formats such as XHTML, RTF, PDF and XSL-FO, using the more low-level
tools. It aims to be a saner replacement, written in Perl, for xmlto, which is
written in Unix shell.

%build
perl Build.PL --installdirs=vendor
./Build

%install
./Build install --destdir="%{buildroot}" --create_packlist=0
%{_fixperms} "%{buildroot}"/*

%check
./Build test

%files
%doc Changes README
%license COPYING
%{perl_vendorlib}/App/
%{_mandir}/man3/App*.3pm*

%files -n docmake
%doc Changes README
%license COPYING
%{_bindir}/docmake
%{_mandir}/man1/docmake.1*

%changelog
* Thu Jul 17 2025 Shlomi Fish <shlomif@shlomifish.org> 0.1101-1
- Specfile autogenerated by cpanspec 1.78.
